### ISSUE TITLE
"Bubbling" distortion when arcs in paths

### ISSUE THREAD

**Issue by apexskier** [nfroidure/svgicons2svgfont#57] opened 2016-05-23 22:56 UTC
I've got a build system that using [gulp-iconfont](https://github.com/nfroidure/gulp-iconfont), and see issues when enabling `convertPathData` in [svgo](https://github.com/svg/svgo/).

Bad: 
![screen shot 2016-05-23 at 3 46 24 pm](https://cloud.githubusercontent.com/assets/329222/15486983/71aead12-20fe-11e6-94a9-f0868b112548.png)

``` svg
<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48">
    <title>
        Fill-1
    </title>
    <path fill="#000" fill-rule="evenodd" d="
        M22.266 33.235
        l3.499-3.471
        a9.684 9.684 0 0 1 1.499 5.206 9.867 9.867 0 0 1-2.851 6.942
        l-3.264 3.235
        C19.296 46.97 16.856 48 14.209 48
        c-2.616 0-5.085-1.03-6.967-2.882
        L2.89 40.764
        c-3.853-3.823-3.853-10.06 0-13.882
        l3.233-3.235
        a9.866 9.866 0 0 1 6.94-2.854
        c1.91 0 3.705.53 5.263 1.53
        l-3.47 3.47
        a5.352 5.352 0 0 0-1.793-.322 5.106 5.106 0 0 0-3.646 1.5
        l-3.235 3.234
        a5.15 5.15 0 0 0 0 7.265
        l4.382 4.353
        c.97.97 2.265 1.5 3.645 1.5
        a5.107 5.107 0 0 0 3.646-1.5
        l3.235-3.235
        c1.44-1.441 1.823-3.53 1.176-5.353
        z
        m11.408-15.59
        l-3.322-3.322-16.29 16.295 3.323 3.323 16.289-16.295
        z
        m11.438 3.472
        l-3.205 3.206
        a9.768 9.768 0 0 1-6.938 2.882 9.674 9.674 0 0 1-5.204-1.5
        l3.468-3.47
        c.559.176 1.117.295 1.736.295 1.382 0 2.645-.53 3.616-1.5
        l3.233-3.236
        a5.147 5.147 0 0 0 0-7.265
        l-4.35-4.353
        a5.116 5.116 0 0 0-3.646-1.5
        c-1.382 0-2.677.53-3.616 1.5
        L26.97 9.412
        c-.97.94-1.5 2.235-1.5 3.617 0 .617.118 1.206.325 1.765
        l-3.47 3.47
        c-1-1.53-1.53-3.353-1.53-5.235
        a9.868 9.868 0 0 1 2.853-6.941
        l3.235-3.236
        A9.86 9.86 0 0 1 33.822 0
        a9.86 9.86 0 0 1 6.938 2.852
        l4.352 4.382
        c3.85 3.824 3.85 10.06 0 13.883
        z"/>
</svg>
```

Good:
![screen shot 2016-05-23 at 3 45 45 pm](https://cloud.githubusercontent.com/assets/329222/15486992/7abf4f9c-20fe-11e6-9beb-aaaa035254cc.png)

``` svg
<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48">
    <title>
        Fill-1
    </title>
    <path fill="#000" fill-rule="evenodd" d="
        M22.2656,33.2348
        L25.7646,29.7638
        C26.7356,31.2938 27.2636,33.0868 27.2636,34.9698
        C27.2636,37.5888 26.2356,40.0578 24.4126,41.9118
        L21.1486,45.1468
        C19.2956,46.9698 16.8556,47.9998 14.2086,47.9998
        C11.5926,47.9998 9.1236,46.9698 7.2416,45.1178
        L2.8896,40.7638
        C-0.9634,36.9408 -0.9634,30.7048 2.8896,26.8818
        L6.1226,23.6468
        C7.9766,21.8228 10.4466,20.7928 13.0626,20.7928
        C14.9736,20.7928 16.7676,21.3228 18.3256,22.3228
        L14.8556,25.7938
        C14.2686,25.5878 13.6806,25.4708 13.0626,25.4708
        C11.6806,25.4708 10.3866,25.9988 9.4166,26.9708
        L6.1816,30.2048
        C4.1826,32.2048 4.1826,35.4698 6.1816,37.4698
        L10.5636,41.8228
        C11.5336,42.7938 12.8286,43.3228 14.2086,43.3228
        C15.5916,43.3228 16.8856,42.7938 17.8546,41.8228
        L21.0896,38.5878
        C22.5306,37.1468 22.9126,35.0588 22.2656,33.2348
        L22.2656,33.2348
        L22.2656,33.2348
        Z
        M33.6736,17.6458
        L30.3516,14.3228
        L14.0626,30.6178
        L17.3846,33.9408
        L33.6736,17.6458
        L33.6736,17.6458
        Z
        M45.1116,21.1168
        L41.9066,24.3228
        C40.0536,26.1748 37.5846,27.2048 34.9686,27.2048
        C33.0866,27.2048 31.2926,26.6768 29.7646,25.7058
        L33.2326,22.2348
        C33.7916,22.4108 34.3496,22.5298 34.9686,22.5298
        C36.3506,22.5298 37.6136,21.9998 38.5846,21.0298
        L41.8176,17.7938
        C43.8186,15.7938 43.8186,12.5288 41.8176,10.5288
        L37.4676,6.1758
        C36.4966,5.2058 35.2036,4.6758 33.8216,4.6758
        C32.4396,4.6758 31.1446,5.2058 30.2056,6.1758
        L26.9696,9.4118
        C26.0006,10.3528 25.4706,11.6468 25.4706,13.0288
        C25.4706,13.6458 25.5876,14.2348 25.7946,14.7938
        L22.3246,18.2648
        C21.3246,16.7348 20.7946,14.9108 20.7946,13.0288
        C20.7946,10.4118 21.8246,7.9408 23.6476,6.0878
        L26.8826,2.8518
        C28.7346,1.0288 31.2046,-0.0002 33.8216,-0.0002
        C36.4376,-0.0002 38.9076,1.0288 40.7596,2.8518
        L45.1116,7.2338
        C48.9626,11.0578 48.9626,17.2938 45.1116,21.1168
        L45.1116,21.1168
        L45.1116,21.1168
        Z"/>
</svg>
```

From my poking around, it seems like this is an issue with arcs (the `a` command in paths), since it seems like the number of arcs in a path corresponds with the  number of artifacts in the resulting font. The svg itself looks find, this only shows up once previewed in my browser (as a woff, I think).

**Comment by Delagen** [comment] 2016-06-15 05:08
+1
Bubbling even on simple images on material-design-icons set

**Comment by Timidfriendly** [comment] 2016-06-30 13:45
+1 
![gulp-icon-bad](https://cloud.githubusercontent.com/assets/1378792/16490392/b937b7b6-3ed9-11e6-849b-745239f1a966.png)
![gulp-icon-better](https://cloud.githubusercontent.com/assets/1378792/16490393/b94ad742-3ed9-11e6-9c21-2a4f2aae8694.png)

**Comment by Delagen** [comment] 2016-06-30 17:52
I rewritten gulp task for use fontforge binary with simple script language. Working fine. No JS project to build even simple svg font from svgs collection without distortion or any proportion loss I found. So I spend some time to write own implementation to produce predictable quality result

**Comment by nfroidure** [comment] 2016-07-01 09:51
Does everyone experiment this issue while combining with svgo ? If yes, why not just remove it since it is not necessar nor useful, svgiconstosvgfont already merge pathes by itself.

If not, try to check if the issue is specific to WOFF/WOFF2 by removing it from your CSS and using either TTF or EOT.

If the issue still remain, try to use an SVGPathData version prior to one of those merges:
- https://github.com/nfroidure/SVGPathData/pull/9
- https://github.com/nfroidure/SVGPathData/pull/11

**Comment by Delagen** [comment] 2016-07-01 12:28
Issue does not related to svgo, svgicons2font project make svg font already broken.Woff and Woff2 produced from ttf which is result of  svgfont. So error in conversion from svgs to svgfont

**Comment by rainfore** [comment] 2016-08-25 14:43
+1

**Comment by moimael** [comment] 2016-10-21 10:43
Same here, also seeing the issue. Any simple workaround ?

**Comment by bryanrasmussen** [comment] 2017-04-21 07:43
@apexskier I was hoping someone knew of a tool to do this from the commandline - any ideas?

**Comment by bryanrasmussen** [comment] 2017-04-21 08:25
agree with @Delagen that it is the conversion - specifically the line 373 of svgicons2fonts/src/index.js 
.ySymetry(glyph.height - options.descent) seems to be the culprit. 

If I remove that the fonts come out fine, only not rotated of course ( I think there may be another problem somewhere - I have a set of icons and in some environments those with arcs are building fine all except for one that builds empty but in the environments that I have complete control over and can follow every svg with arcs in it end up messed up looking and the ySymetry function seems to be responsible).

@Delagen  said you have a fixed build somewhere - where is that?

**Comment by nfroidure** [comment] 2017-04-21 08:45
I reported the issue to the related project. @NaridaL made huge improvements recently on SVGPathData. You may try to update it and check if it works for you.
https://github.com/nfroidure/SVGPathData/commits/master

That said, this project is not actively maintained since I do not use it but I always give repository access to anyone making a significant PR on it so feel free to suggest changes via PRs.

**Comment by nfroidure** [comment] 2017-04-21 15:37
According to this comment, you should really try to update SVGPathData version and try again with it: https://github.com/nfroidure/SVGPathData/issues/24#issuecomment-296218904

Otherwise, did you try to remove the woff/woff2 font as mentioned earlyer to see if the problem sits in the ttf to woff tranformations ?

**Comment by bryanrasmussen** [comment] 2017-04-21 16:49
@nfroidure assuming that the bug I've been experiencing is the bubbling bug here (it is only found in svgs with arcs and there are distortions that seem to match the number of arcs found (seem because I only really counted the arcs in one and said huh looks legit) then it is definitely not the ttf to woff transform because it exists in the svg when I open the svg font up in fontforge. Also I can stop the distortion of the font by removing the line of code I mentioned earlier but then the problem is that all icons have not been flipped as needed. I will try to update svgPAthData version this weekend and look at it. Thanks.

**Comment by Delagen** [comment] 2017-08-24 08:57
@bryanrasmussen I use fontforge as converter via scripting api.

- spawn fontforge
- generate script and write it to stdin
- wait for close
- get svg font

I can provide some node.js example wrapper

**Comment by bryanrasmussen** [comment] 2017-08-24 09:58
that's basically what I do, the update to svgPathData seems to have fixed
the problem so I will close the issu (wasn't aware was still open )

**Comment by bryanrasmussen** [comment] 2017-08-24 09:58
oops, never mind thought this was an issue I had opened. :)

On Thu, Aug 24, 2017 at 11:57 AM, bryan rasmussen <rasmussen.bryan@gmail.com
> wrote:

> that's basically what I do, the update to svgPathData seems to have fixed
> the problem so I will close the issu (wasn't aware was still open )
>
> On Thu, Aug 24, 2017 at 10:57 AM, Vohmyanin Sergey Vasilevich <

**Comment by NaridaL** [comment] 2017-08-24 13:38
@nfroidure Considering the latest svg-pathdata version seems to solve this, can you publish 7.0.0 (and 6.0.1) so we can close this issue?

**Comment by nfroidure** [comment] 2017-08-24 14:00
@NaridaL just added you as an owner in NPM, I'll publish when possible otherwise.

**Comment by NaridaL** [comment] 2017-08-24 14:10
@nfroidure That works too, I published it! Btw, if you give me write access to the dependents, I'll update this dependency if I have time.

**Closed by NaridaL** 2017-08-24 14:10 UTC
Labels: bug

**Comment by nfroidure** [comment] 2017-08-24 14:24
Just did it both on NPM and GH.

Thank you very much for all your valuable efforts on those projects!

**Comment by NaridaL** [comment] 2017-08-24 15:21
@nfroidure You're welcome.

Just tried doing it in gulp-svgicons2svgfont, and there's a race condition causing tests to fail 80% of the time... so that will probably have to wait XD
